<?php
class Core {

    public function run()
    {
        ob_start();
        require_once('index.php');
        ob_get_flush();     //return the value generated by the code as a normal string
    }
}
