<?php
class Core {

    /**
     * Run method base
     */
    public function run()
    {
        ob_start();
        require_once(Url::getPage());
        ob_get_flush();     //return the value generated by the code as a normal string
    }
}
